def run() -> int:
    print()
    print("It is suggested to Select-String/grep this output to find if your desired function is present.")
    print("Select-String can be done with: KDMM List | Select-String -Pattern <FUNCTION>")
    print()
    print("You can enter <quit> in any function to exit back to the terminal.")
    print()
    print("The functions avilable are:")
    print("length-convert - Allows you to convert from one unit of length to another.")
    print("weight-convert - Allows you to convert from one unit of weight to another.")
    print("hypot-calc - Calculates the hypotenuse of a right triangle from two given legs.")
    print("mleg-calc - Calculates the missing leg of a right triangle using the hypotenuse and the given leg.")
    print("center-dist - Calculates the center distance of a pulley system.")
    print("subdivision - Calculates the distances between sub-divisions in walls")
    print()
    return 0
